name: Build and deploy Python app to Azure Web App - yib-fastapi1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r MyFastAPIApp/requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E47386B5B9F34981883864F1159B9585 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E9DE3FFACD1A48C7A4ADEC31BA646CAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37FEF6B8533C4B7194F68DB11D5A5013 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'yib-fastapi1'
          slot-name: 'Production'
          package: ./MyFastAPIApp
